"""
One regulatory warning per withdrawal event, not one per data row.

data/regulatory_withdrawals.json is regenerated by an automated updater, and
a single withdrawal can arrive as several rows (one per regulator). Both the
/query answer and the treatment card matched every row independently, so
atezolizumab produced two near-identical warnings saying the same thing.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from src.generation.card_generator import (
    TreatmentTriplet,
    _apply_regulatory_to_triplets,
)
from src.generation.post_process import (
    apply_regulatory_warnings,
    regulatory_dedupe_key,
)

_DATA = Path("data/regulatory_withdrawals.json")

# The pre-fix shape: the same withdrawal split across two regulators.
_SPLIT_ROWS = (
    {
        "drug": "atezolizumab",
        "aliases": ["tecentriq"],
        "indication": "first-line platinum-ineligible urothelial carcinoma",
        "indication_keywords": ["urothelial"],
        "jurisdiction": "EMA",
        "warning": "EMA withdrew it.",
        "warning_fr": "L'EMA l'a retiree.",
    },
    {
        "drug": "atezolizumab",
        "aliases": ["tecentriq"],
        "indication": "first-line platinum-ineligible urothelial carcinoma",
        "indication_keywords": ["urothelial"],
        "jurisdiction": "FDA",
        "warning": "FDA withdrew it.",
        "warning_fr": "La FDA l'a retiree.",
    },
)

_ANSWER = "Atezolizumab is an option in urothelial carcinoma."


def test_dedupe_key_matches_across_jurisdictions():
    a, b = _SPLIT_ROWS
    assert regulatory_dedupe_key(a) == regulatory_dedupe_key(b)


def test_dedupe_key_separates_different_indications():
    a = {"drug": "atezolizumab", "indication": "urothelial"}
    b = {"drug": "atezolizumab", "indication": "hepatocellular"}
    assert regulatory_dedupe_key(a) != regulatory_dedupe_key(b)


# ── /query path ───────────────────────────────────────────────────────────────

def test_query_emits_one_warning_for_split_rows():
    with patch("src.generation.post_process._load_withdrawals", return_value=_SPLIT_ROWS):
        out = apply_regulatory_warnings(_ANSWER, language="en")
    assert out.count("Regulatory note") == 1


def test_query_still_warns_for_distinct_drugs():
    rows = (
        _SPLIT_ROWS[0],
        {
            "drug": "rucaparib",
            "aliases": [],
            "indication": "BRCA-mutated metastatic CRPC",
            "indication_keywords": ["urothelial"],
            "warning": "Rucaparib withdrawn.",
        },
    )
    with patch("src.generation.post_process._load_withdrawals", return_value=rows):
        out = apply_regulatory_warnings(
            "Atezolizumab and rucaparib in urothelial carcinoma.", language="en"
        )
    assert out.count("Regulatory note") == 2


def test_query_answer_without_a_match_is_untouched():
    with patch("src.generation.post_process._load_withdrawals", return_value=_SPLIT_ROWS):
        assert apply_regulatory_warnings("Nothing relevant here.") == "Nothing relevant here."


# ── treatment-card path ───────────────────────────────────────────────────────

def test_card_cell_gets_one_alert_for_split_rows():
    triplet = TreatmentTriplet(drug="Atezolizumab", intent="Palliative", level="B", warnings=[])
    with patch("src.generation.card_generator._load_withdrawals", return_value=_SPLIT_ROWS):
        _apply_regulatory_to_triplets([triplet], "urothelial carcinoma", "en")
    assert len(triplet.warnings) == 1


def test_card_dedupes_per_triplet_not_globally():
    """Two treatments naming the same drug should each still carry its warning."""
    a = TreatmentTriplet(drug="Atezolizumab mono", intent="Palliative", level="B", warnings=[])
    b = TreatmentTriplet(drug="Atezolizumab + chemo", intent="Palliative", level="C", warnings=[])
    with patch("src.generation.card_generator._load_withdrawals", return_value=_SPLIT_ROWS):
        _apply_regulatory_to_triplets([a, b], "urothelial carcinoma", "en")
    assert len(a.warnings) == 1
    assert len(b.warnings) == 1


# ── the shipped data file ─────────────────────────────────────────────────────

def test_shipped_data_has_no_duplicate_events():
    entries = json.loads(_DATA.read_text())["entries"]
    keys = [regulatory_dedupe_key(e) for e in entries]
    assert len(keys) == len(set(keys)), f"duplicate withdrawal events: {keys}"


def test_shipped_atezolizumab_entry_cites_no_trial():
    """
    IMVIGOR110 and IMVIGOR010 were both wrong here -- IMvigor010 is the
    adjuvant trial, not the basis for this first-line withdrawal. Rather than
    swap in another trial name, the entry cites none.
    """
    entries = json.loads(_DATA.read_text())["entries"]
    atz = [e for e in entries if e["drug"] == "atezolizumab"]
    assert len(atz) == 1
    text = (atz[0]["warning"] + atz[0].get("warning_fr", "")).lower()
    assert "imvigor" not in text
    assert "ema" in text and "fda" in text


# ── Weekly updater must not reintroduce the duplicate ─────────────────────────
#
# scripts/update_regulatory_db.py runs on a weekly cron. It dedupes on
# (drug, jurisdiction), so it will add an "FDA" row next to the curated
# "EMA/FDA" one, with indication "see product description" and an EMPTY
# indication_keywords list -- which fires on every answer naming the drug.

from src.generation.post_process import _collapse_withdrawal_rows

_CURATED = {
    "drug": "atezolizumab",
    "aliases": ["tecentriq"],
    "indication": "first-line platinum-ineligible urothelial carcinoma",
    "indication_keywords": ["urothelial"],
    "jurisdiction": "EMA/FDA",
    "warning": "Curated warning.",
}
_AUTO = {
    "drug": "atezolizumab",
    "aliases": [],
    "indication": "see product description",
    "indication_keywords": [],
    "jurisdiction": "FDA",
    "warning": "Automated warning.",
}


def test_automated_row_dropped_when_curated_row_covers_the_drug():
    assert _collapse_withdrawal_rows((_CURATED, _AUTO)) == (_CURATED,)


def test_collapse_is_order_independent():
    assert _collapse_withdrawal_rows((_AUTO, _CURATED)) == (_CURATED,)


def test_automated_row_kept_for_a_drug_with_no_curated_entry():
    novel = dict(_AUTO, drug="somenewdrug")
    kept = _collapse_withdrawal_rows((_CURATED, novel))
    assert novel in kept, "a genuinely new withdrawal must still warn"


def test_updater_output_yields_one_warning_end_to_end():
    with patch("src.generation.post_process._load_withdrawals",
               return_value=_collapse_withdrawal_rows((_CURATED, _AUTO))):
        out = apply_regulatory_warnings(_ANSWER, language="en")
    assert out.count("Regulatory note") == 1
    assert "Automated warning." not in out


def test_ungated_automated_row_would_otherwise_fire_on_anything():
    """Documents why the collapse matters: empty keywords means no gating."""
    with patch("src.generation.post_process._load_withdrawals", return_value=(_AUTO,)):
        out = apply_regulatory_warnings("Atezolizumab in hepatocellular carcinoma.")
    assert out.count("Regulatory note") == 1  # fires despite the wrong indication
